task and contribution for sprint 3
Heidrun7/group-5-smce-gd pull request #20
Opened 2021-11-03 17:29 UTC by birgittab

2021-11-03 18:00 UTC, Heidrun7 approved these changes

2021-11-04 00:26 UTC, Heidrun7 requested changes
Shouldn't we update it to include the new tasks as well?

2021-11-04 09:03 UTC, Asad-Meraj approved these changes
Merged

2021-11-04 09:16 UTC, Heidrun7 approved these changes

2021-11-04 13:58 UTC, merged